### ISSUE TITLE
Example config files

### ISSUE THREAD

**Issue by dannyloxavier** [stevenengler/no-js-hugo-theme#1]
Dear developer, is it possible to have an exampleSite or some sort of config.toml example at README.md?

**Comment by stevenengler** [comment]
Sure, added one: https://github.com/stevenengler/no-js-hugo-theme/tree/master/exampleSite

There aren't a lot of options. Any non-standard options are listed in the config.toml.

**Comment by stevenengler** [comment]
Also added a rendered example: https://stevenengler.github.io/no-js-hugo-theme-example/
