### ISSUE TITLE
Add headers to tell LibreJS that the theme switcher.js is freely licensed

### ISSUE THREAD

**Issue by Skivling** [stevenengler/no-js-hugo-theme#5]
This is one of the only Hugo themes which do not require Javascript, and the only script it has is the theme switcher. Everything is MIT-licensed, so I request that the JS file be marked as freely licensed so it can be detected by LibreJS firefox add-on.
People using GNU IceCat or LibreJS web add-on block all javascript that is not verified to be freely licensed. 
I think you can just add a special comment at the top, see Step 3 part 3.2.3/4 of: https://www.gnu.org/software/librejs/free-your-javascript.html
It may be worth reading [the JavaScript Trap](https://www.gnu.org/philosophy/javascript-trap.html) as well.

I was going to do this to my website, but it would be more beneficial if it was built into the theme.

**Comment by stevenengler** [comment]
Sure, added it in 346b761.
